jobs:
  include:
    - language: python
      python: 3.8
      before_install:
        - cd api
      script:
        - pytest
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build jfeudeline/codenames-api .
        - docker push jfeudeline/codenames-api

    - language: node_js
      node_js: 13
      before_install:
        - cd ui
      script:
        - yarn build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build jfeudeline/codenames-ui .
        - docker push jfeudeline/codenames-ui
