jobs:
  include:
    - language: python
      python: 3.8
      before_install:
        - cd api
      script:
        - pytest
        - docker build jfeudeline/codenames-api .
        - docker push jfeudeline/codenames-api
      deploy:
        provider: ${PROVIDER}
        api_key: ${HEROKU_API_KEY}
        app: ${API_APP}
        on: master

    - language: node_js
      node_js: 13
      before_install:
        - cd ui
      script:
        - yarn build
        - docker build jfeudeline/codenames-ui .
        - docker push jfeudeline/codenames-ui
      deploy:
        provider: ${PROVIDER}
        api_key: ${HEROKU_API_KEY}
        app: ${UI_APP}
        on: master
