jobs:
  include:
    - language: python
      python: 3.8
      before_install:
        - cd api
      script:
        - pytest
      deploy:
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-api:latest . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-api:latest
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-api$TRAVIS_TAG . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-api$TRAVIS_TAG
          on:
            branch: master

    - language: node_js
      node_js: 13
      before_install:
        - cd ui
      script:
        - yarn build

      deploy:
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-ui:latest . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-ui:latest
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-ui$TRAVIS_TAG . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-ui$TRAVIS_TAG
          on:
            branch: master
