jobs:
  include:
    - language: python
      python: 3.8
      before_intall:
        - cd api
      script:
        - pytest

    - language: node_js
      node_js: 13
      before_intall:
        - cd ui
      script:
        - yarn test
      deploy:
        provider: pages:git
        token: $PAGES_TOKEN
        edge: true
