jobs:
  include:
    - language: python
      python: 3.8
      before_install:
        - cd api
      script:
        - pytest
      deploy:
        provider: ${PROVIDER}
        api_key: ${HEROKU_API_KEY}
        app: ${API_APP}
        on: master

    - language: node_js
      node_js: 13
      before_install:
        - cd ui
      script:
        - yarn test
      before_install:
        - cd ui
      deploy:
        provider: ${PROVIDER}
        api_key: ${HEROKU_API_KEY}
        app: ${UI_APP}
        on: master
