jobs:
  include:
    - language: python
      python: 3.8
      before_install:
        - cd api
      script:
        - pytest
      deploy:
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-api:latest . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-api:latest
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-api$TRAVIS_TAG . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-api$TRAVIS_TAG
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com && docker tag jfeudeline/codenames-api:latest registry.heroku.com/powerful-scrubland-30965/web && docker push registry.heroku.com/powerful-scrubland-30965/web #&& curl --netrc -X PATCH https://api.heroku.com/apps/powerful-scrubland-30965/formation -d '{"updates": [{"type": "web", "docker_image": "jfeudeline/codenames-api:latest"}]}' -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
          on:
            branch: master

    - language: node_js
      node_js: 13
      before_install:
        - cd ui
      script:
        - yarn build

      deploy:
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-ui:latest . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-ui:latest
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script: docker build -t jfeudeline/codenames-ui$TRAVIS_TAG . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jfeudeline/codenames-ui$TRAVIS_TAG
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com && docker tag jfeudeline/codenames-ui:latest registry.heroku.com/jfeudeline-codenames/web && docker push registry.heroku.com/jfeudeline-codenames/web #&& curl --netrc -X PATCH https://api.heroku.com/apps/jfeudeline-codenames/formation -d '{"updates": [{"type": "web", "docker_image": "jfeudeline/codenames-ui:latest"}]}' -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
          on:
            branch: master
