jobs:
  include:
    - language: python
      python: 3.8
      script:
        - cd api
        - pytest

    - language: node_js
      node_js: 13
      script:
        - node -e "console.log('Hi from NodeJS!')"
